from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class VectorStoreBackend(Protocol):
    def add_qa_pair(self, question: str, sql: str, metadata: dict | None = None) -> str: ...

    def add_ddl(self, ddl: str, table_name: str = "") -> str: ...

    def add_documentation(self, doc: str, metadata: dict | None = None) -> str: ...

    def add_finding(self, finding: str, metadata: dict | None = None) -> str: ...

    def search_qa(self, question: str, n: int = 5) -> list[dict]: ...

    def search_ddl(self, question: str, n: int = 3) -> list[dict]: ...

    def search_docs(self, question: str, n: int = 3) -> list[dict]: ...

    def search_findings(self, question: str, n: int = 3) -> list[dict]: ...

    def delete_all(self) -> dict[str, int]: ...
