"""Schema migration constants: columns and indexes applied idempotently at startup."""

# New tables to create if they don't exist
MIGRATION_TABLES = [
    """CREATE TABLE IF NOT EXISTS external_database_connections (
        id VARCHAR(36) PRIMARY KEY,
        organization_id VARCHAR(100),
        name VARCHAR(255) NOT NULL,
        connection_type VARCHAR(20) NOT NULL,
        host VARCHAR(255) NOT NULL,
        port INTEGER NOT NULL,
        database VARCHAR(255) NOT NULL,
        username VARCHAR(255) NOT NULL,
        password VARCHAR(255) NOT NULL,
        is_active BOOLEAN DEFAULT FALSE NOT NULL,
        is_verified BOOLEAN DEFAULT FALSE NOT NULL,
        last_verified_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE SET NULL
    )""",
    """CREATE TABLE IF NOT EXISTS user_database_connections (
        id VARCHAR(36) PRIMARY KEY,
        user_id VARCHAR(36) NOT NULL,
        name VARCHAR(255) NOT NULL,
        connection_string TEXT NOT NULL,
        is_active BOOLEAN DEFAULT FALSE NOT NULL,
        is_verified BOOLEAN DEFAULT FALSE NOT NULL,
        last_verified_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    )""",
]

# Migration columns: (table, column, column_def).
MIGRATION_COLUMNS = [
    ("users", "is_admin", "BOOLEAN DEFAULT FALSE NOT NULL"),
    ("users", "last_active", "TIMESTAMP"),
    ("users", "org_id", "VARCHAR(100)"),
    ("users", "updated_at", "TIMESTAMP"),
    ("conversations", "is_starred", "BOOLEAN DEFAULT FALSE NOT NULL"),
    ("conversations", "org_id", "VARCHAR(100)"),
    ("messages", "feedback", "BOOLEAN"),
    ("messages", "feedback_comment", "TEXT"),
    ("messages", "input_tokens", "INTEGER"),
    ("messages", "output_tokens", "INTEGER"),
    ("messages", "generation_time_ms", "INTEGER"),
    ("automations", "workflow_json", "TEXT"),
    ("automations", "org_id", "VARCHAR(100)"),
    ("trigger_templates", "org_id", "VARCHAR(100)"),
    ("datasets", "organization_id", "VARCHAR(100)"),
    ("datasets", "created_by", "VARCHAR(36) REFERENCES users(id) ON DELETE SET NULL"),
    ("datasets", "r2_key", "VARCHAR(500)"),
    ("insights", "user_note", "TEXT"),
    ("insights", "source", "VARCHAR(20) DEFAULT 'auto'"),
]

# All indexes and unique constraints that must exist on every database.
SCHEMA_INDEXES = [
    "CREATE INDEX IF NOT EXISTS ix_conversations_user_id ON conversations (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_conversations_updated_at ON conversations (updated_at)",
    "CREATE INDEX IF NOT EXISTS ix_conversations_org_id ON conversations (org_id)",
    "CREATE INDEX IF NOT EXISTS ix_messages_conversation_id ON messages (conversation_id)",
    "CREATE INDEX IF NOT EXISTS ix_messages_created_at ON messages (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_messages_conv_created ON messages (conversation_id, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_automation_runs_automation_id ON automation_runs (automation_id)",
    "CREATE INDEX IF NOT EXISTS ix_automation_runs_auto_created ON automation_runs (automation_id, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_automations_active_next_run ON automations (is_active, next_run_at)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_user_id ON notifications (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_notifications_user_read ON notifications (user_id, is_read, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_dataset_stats_stat_group ON dataset_stats (stat_group)",
    "CREATE INDEX IF NOT EXISTS ix_dataset_stats_group_dim ON dataset_stats (stat_group, dimension)",
    "CREATE INDEX IF NOT EXISTS ix_datasets_organization_id ON datasets (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_datasets_created_by ON datasets (created_by)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_dataset_columns_ds_col ON dataset_columns (dataset_id, column_name)",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_example_queries_ds_question ON example_queries (dataset_id, question)",
    "CREATE INDEX IF NOT EXISTS ix_automations_org_id ON automations (org_id)",
    "CREATE INDEX IF NOT EXISTS ix_automations_org_created ON automations (org_id, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_automation_triggers_auto_id ON automation_triggers (automation_id)",
    "CREATE INDEX IF NOT EXISTS ix_trigger_templates_org_id ON trigger_templates (org_id)",
    "CREATE INDEX IF NOT EXISTS ix_trigger_templates_created_by ON trigger_templates (created_by)",
    "CREATE INDEX IF NOT EXISTS ix_enrichment_traces_message ON enrichment_traces (message_id)",
    "CREATE INDEX IF NOT EXISTS ix_insights_user_id ON insights (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_insights_org_id ON insights (org_id)",
    "CREATE INDEX IF NOT EXISTS ix_insights_user_created ON insights (user_id, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_insights_org_created ON insights (org_id, created_at)",
    "CREATE INDEX IF NOT EXISTS ix_insights_created_at ON insights (created_at)",
    "CREATE INDEX IF NOT EXISTS ix_external_db_org_id ON external_database_connections (organization_id)",
    "CREATE INDEX IF NOT EXISTS ix_external_db_active ON external_database_connections (organization_id, is_active)",
    "CREATE INDEX IF NOT EXISTS ix_user_db_conn_user_id ON user_database_connections (user_id)",
    "CREATE INDEX IF NOT EXISTS ix_user_db_conn_user_active ON user_database_connections (user_id, is_active)",
]
